#!/usr/bin/env python3

# Load the pylit module::

import pylit

# Configure default settings, e.g. ::

## pylit.defaults.code_block_marker['c++'] = '.. code-block:: c++'

# call the text <--> code converter::

pylit.main()
